### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by ghost** [OctoPrint/OctoPrint-RequestSpinner#1]
Installing plugin from https://github.com/OctoPrint/OctoPrint-RequestSpinner/archive/master.zip...
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Collecting https://github.com/OctoPrint/OctoPrint-RequestSpinner/archive/master.zip
InsecurePlatformWarning
/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Downloading https://github.com/OctoPrint/OctoPrint-RequestSpinner/archive/master.zip
InsecurePlatformWarning
Complete output from command python setup.py egg_info:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-5wQ6eF-build
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-5wQ6eF-build/setup.py", line 87, in <module>
additional_data=plugin_additional_data
TypeError: create_plugin_setup_parameters() got an unexpected keyword argument 'package'

**Comment by foosel** [comment]
Please upgrade your installed OctoPrint version, RequestSpinner requires the released 1.2.0 and you are apparently still running some older devel version or that would not fail.

**Comment by ghost** [comment]
Version: 1.2.0-dev-893-gb04be6d (devel branch)

**Comment by foosel** [comment]
1.2.0-dev-893 is a development (hence the -dev) version from maybe 3 weeks ago. RequestSpinner was written to run with the release version of 1.2.0. Upgrade your OctoPrint installation. 

Sorry, but I can't keep things backwards compatible to every unreleased intermediary development version there ever was. If you run devel, upgrade regularly, at least do so when plugins don't work.

**Comment by ghost** [comment]
Something about Git screwed up then, because I pulled that update yesterday... I'll try again.

**Comment by foosel** [comment]
Make sure you also installed it with ~/oprint/bin/python setup.py install, only pulling the new sources isn't enough (just making sure, sorry if stating the already obvious). When you run OctoPrint it should tell you the version it's at in the log as one of the first things when starting up (and of course also in the UI). Current devel should report something like 1.3.0-dev-6 (unsure about the 6, could be a higher or lower number there too)
